import isaaclab.terrains as terrain_gen
import isaaclab.terrains.height_field as hf_gen
from isaaclab.terrains import FlatPatchSamplingCfg,

INDOOR_NAVIGATION_CFG = terrain_gen.TerrainGeneratorCfg(
    size=(8.0, 8.0),
    border_width=20.0,
    num_rows=5,
    num_cols=5,
    horizontal_scale=0.05,
    vertical_scale=0.1,
    slope_threshold=0.75,
    difficulty_range=(0.0, 1.0),
    use_cache=False,
    sub_terrains={
        "medium_density": hf_gen.HfDiscreteObstaclesTerrainCfg(
            size=(2.0, 2.0),
            horizontal_scale=0.05,
            vertical_scale=0.1,
            num_obstacles=20,
            obstacle_width_range=(0.5, 1.5),
            obstacle_height_range=(1.0, 1.0),
            platform_width=2.0,
            border_width=0.3,
            obstacle_height_mode="fixed",
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=5,
                    x_range=(-2, 2),
                    y_range=(-2, 2),
                    z_range=(-0.1, 0.1),
                    patch_radius=0.5,
                    max_height_diff=0.05,
                ),
            },
        ),
        "less_density": hf_gen.HfDiscreteObstaclesTerrainCfg(
            size=(2.0, 2.0),
            horizontal_scale=0.05,
            vertical_scale=0.1,
            num_obstacles=3,
            obstacle_width_range=(1.5, 2.5),
            obstacle_height_range=(1.0, 1.0),
            platform_width=2.0,
            border_width=0.3,
            obstacle_height_mode="fixed",
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=5,
                    x_range=(-2, 2),
                    y_range=(-2, 2),
                    z_range=(-0.1, 0.1),
                    patch_radius=0.5,
                    max_height_diff=0.05,
                ),
            },
        ),
        "more_density": hf_gen.HfDiscreteObstaclesTerrainCfg(
            size=(2.0, 2.0),
            horizontal_scale=0.05,
            vertical_scale=0.1,
            num_obstacles=50,
            obstacle_width_range=(0.5, 0.8),
            obstacle_height_range=(1.0, 1.0),
            platform_width=2.0,
            border_width=0.3,
            obstacle_height_mode="fixed",
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=5,
                    x_range=(-2, 2),
                    y_range=(-2, 2),
                    z_range=(-0.1, 0.1),
                    patch_radius=0.5,
                    max_height_diff=0.05,
                ),
            },
        ),
    },
)